name = "Rosenbrock"
uuid = "c23fb45c-8f64-40e4-b594-aa994fe44f9b"
authors = ["Ali Siahkoohi <ali.siahkoohi@gmail.com>"]
version = "0.1.0"

[deps]
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
