name = "Rosenbrock"
uuid = "729bb193-69ad-4b73-b984-a9996674366f"
authors = ["Ali Siahkoohi <ali.siahkoohi@gmail.com>"]
version = "0.1.0"

[deps]
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
